apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scotch-20190225-dep
  labels:
    #Project ID
    app: scotch-20190225
spec:
  #Run two instances of our application
  replicas: 2
  template:
    metadata:
      labels:
        app: scotch-20190225
    spec:
      #Container details
      containers:
        - name: node-app
          image: gcr.io/scotch-20190225/node-app:0.0.1
          imagePullPolicy: Always
          #Ports to expose
          ports:
          - containerPort: 8000
          env:
          # Name of the environment variable as will be in the Pod
            - name: IG_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                    # Name of the secret
                    name: scotch-20190225-secret
                    # key of the value stored in the secret
                    key: access_token          