kind: Service
apiVersion: v1
metadata:
  #Service name
  name: node-app-svc
spec:
  selector:
    app: scotch-20190225
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer