# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:lts

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

  deploy:
    docker:
      - image: google/cloud-sdk
        environment:
          PROJECT_ID: scotch-20190225
          CLUSTER_NAME: scotch-20190225-cluster-1
          COMPUTE_ZONE: europe-north1-c
          COMPUTE_REGION: europe-north1
          #As specified in Deployment.yml
          DEPLOYMENT_NAME: scotch-20190225-dep
          CONTAINER_NAME: node-app

    working_directory: ~/repo

    steps:
      - checkout

      #- run: gcloud --quiet components update --version 236.0.0

      - run:
          name: Deploy to Google Cloud 
          command: |
            echo $SERVICE_KEY > key.txt
            base64 -i key.txt -d > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account ${ACCOUNT_ID} --key-file ${HOME}/gcloud-service-key.json
            gcloud config set project $PROJECT_ID
            gcloud --quiet config set container/cluster $CLUSTER_NAME
            gcloud config set compute/region $COMPUTE_REGION
            gcloud --quiet container clusters get-credentials $CLUSTER_NAME
            service docker start
            docker build -t gcr.io/${PROJECT_ID}/node-app:$CIRCLE_SHA1 .
            gcloud docker -- push gcr.io/${PROJECT_ID}/node-app:$CIRCLE_SHA1
            kubectl set image deployment/${DEPLOYMENT_NAME} ${CONTAINER_NAME}=gcr.io/${PROJECT_ID}/node-app:$CIRCLE_SHA1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build