# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:lts

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

  deploy:
    docker:
      - image: ubuntu:latest
        environment:
          PROJECT_ID: scotch-20190225
          CLUSTER_NAME: scotch-20190225-cluster-1
          COMPUTE_ZONE: europe-north1-c
          COMPUTE_REGION: europe-north1
          #As specified in Deployment.yml
          DEPLOYMENT_NAME: scotch-20190225-dep
          CONTAINER_NAME: node-app

    working_directory: ~/repo

    steps:
      - checkout

      #- run: gcloud --quiet components update --version 236.0.0

      - run:
          name: Install Google Cloud-SDK 0
          command: |
            apt-get update
            apt-get -y install apt-utils curl lsb-release gnupg2

      - run:
          name: Install Google Cloud-SDK 1
          command: |
            echo 'export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"' >> $BASH_ENV

      - run:
          name: Install Google Cloud-SDK 2
          command: |
            apt-get update
            apt-get -y install apt-transport-https
            echo "deb https://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

      - run:
          name: Install Google Cloud-SDK 3
          command: |
            apt-get update
            apt-get -y install google-cloud-sdk kubectl

      - run:
          name: Install Docker 
          command: |
            apt-get update
            apt-get -y install apt-transport-https ca-certificates curl gnupg2 software-properties-common

      - run:
          name: Install Docker 2
          command: |
            curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
            add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
            apt-get update 
            apt-get -y install docker-ce docker-ce-cli containerd.io

      - run:
          name: Deploy to Google Cloud 
          command: |
            echo $SERVICE_KEY > key.txt
            base64 -i key.txt -d > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account ${ACCOUNT_ID} --key-file ${HOME}/gcloud-service-key.json
            gcloud config set project $PROJECT_ID
            gcloud --quiet config set container/cluster $CLUSTER_NAME
            gcloud config set compute/region $COMPUTE_REGION
            gcloud --quiet container clusters get-credentials $CLUSTER_NAME --region $COMPUTE_REGION

      - run:
          name: Deploy to Google Cloud 2
          command: |
            service docker start
            docker build -t gcr.io/${PROJECT_ID}/node-app:$CIRCLE_SHA1 .

      - run:
          name: Deploy to Google Cloud 3
          command: |
            gcloud docker -- push gcr.io/${PROJECT_ID}/node-app:$CIRCLE_SHA1

      - run:
          name: Deploy to Google Cloud 4
          command: |
            kubectl set image deployment/${DEPLOYMENT_NAME} ${CONTAINER_NAME}=gcr.io/${PROJECT_ID}/node-app:$CIRCLE_SHA1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build